"""msg

Revision ID: da44237e7522
Revises: d3f9fd90f4ea
Create Date: 2025-09-13 14:06:56.419746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da44237e7522'
down_revision: Union[str, Sequence[str], None] = 'd3f9fd90f4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_documents_s_id'), 'documents', ['s_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_s_id'), table_name='documents')
    op.drop_column('documents', 's_id')
    # ### end Alembic commands ###
